version: "3"

services:
    nginx:
        build:
            context: docker/nginx
        volumes:
            - ./public:/var/www/symfony/public/:cached
        ports:
            - 8080:80
        depends_on:
            - php

    php:
        build:
            context: docker/php
        environment:
            APP_ENV: dev
        volumes:
            - .:/var/www/symfony/:cached
            - /var/www/symfony/vendor
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - ./docker/db/data/postgres:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        ports:
            - 8081:8080
